//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenXBL.Resources.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XboxLiveApi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XboxLiveApi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenXBL.Resources.Text.XboxLiveApi", typeof(XboxLiveApi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string AcceptHeader {
            get {
                return ResourceManager.GetString("AcceptHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string AcceptJson {
            get {
                return ResourceManager.GetString("AcceptJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-RateLimit-Limit.
        /// </summary>
        internal static string ApiLimitHeader {
            get {
                return ResourceManager.GetString("ApiLimitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-RateLimit-Remaining.
        /// </summary>
        internal static string ApiRemainingHeader {
            get {
                return ResourceManager.GetString("ApiRemainingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-RateLimit-Spent.
        /// </summary>
        internal static string ApiUsedHeader {
            get {
                return ResourceManager.GetString("ApiUsedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Authorization.
        /// </summary>
        internal static string AuthHeader {
            get {
                return ResourceManager.GetString("AuthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://xbl.io/api/v2.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type.
        /// </summary>
        internal static string ContentTypeHeader {
            get {
                return ResourceManager.GetString("ContentTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Contract.
        /// </summary>
        internal static string ContractHeader {
            get {
                return ResourceManager.GetString("ContractHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string ContractHeaderValue {
            get {
                return ResourceManager.GetString("ContractHeaderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://xbl.io/app/auth/.
        /// </summary>
        internal static string OAuthUrl {
            get {
                return ResourceManager.GetString("OAuthUrl", resourceCulture);
            }
        }
    }
}
